name: Tests

on:
  push:
    branches:
      - master
      - gake
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
